# 生产环境配置 (master namespace)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://154.201.68.122:3306/springcloud_demo?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: app_user
    password: App@Remote2026#User
  cloud:
    nacos:
      discovery:
        server-addr: 154.201.68.122:8848
        namespace: master
        username: nacos
        password: nacos

datasource:
  master:
    url: jdbc:mysql://154.201.68.122:3306/springcloud_demo_master?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: app_user
    password: App@Remote2026#User
