-- encrypt_table_config
CREATE TABLE encrypt_table_config (
    id          NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name  VARCHAR2(128) NOT NULL UNIQUE,
    batch_size  NUMBER(10) DEFAULT 1000,
    batch_interval_ms NUMBER(10) DEFAULT 0,
    enabled     NUMBER(1) DEFAULT 1,
    create_time TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE encrypt_table_config IS '加密表配置';
COMMENT ON COLUMN encrypt_table_config.id IS '主键';
COMMENT ON COLUMN encrypt_table_config.table_name IS '目标表名';
COMMENT ON COLUMN encrypt_table_config.batch_size IS '批次大小';
COMMENT ON COLUMN encrypt_table_config.batch_interval_ms IS '批次间隔(毫秒)';
COMMENT ON COLUMN encrypt_table_config.enabled IS '是否启用(1=启用,0=禁用)';
COMMENT ON COLUMN encrypt_table_config.create_time IS '创建时间';
COMMENT ON COLUMN encrypt_table_config.update_time IS '更新时间';

-- encrypt_field_config
CREATE TABLE encrypt_field_config (
    id              NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_config_id NUMBER(20) NOT NULL,
    field_name      VARCHAR2(128) NOT NULL,
    algorithm_id    VARCHAR2(64),
    field_order     NUMBER(10) NOT NULL,
    skip_encrypted  NUMBER(1) DEFAULT 1,
    create_time     TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP,
    update_time     TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_field_table_config FOREIGN KEY (table_config_id) REFERENCES encrypt_table_config(id) ON DELETE CASCADE
);

COMMENT ON TABLE encrypt_field_config IS '字段加密配置';
COMMENT ON COLUMN encrypt_field_config.id IS '主键';
COMMENT ON COLUMN encrypt_field_config.table_config_id IS '关联表配置ID';
COMMENT ON COLUMN encrypt_field_config.field_name IS '字段名';
COMMENT ON COLUMN encrypt_field_config.algorithm_id IS '加密算法标识';
COMMENT ON COLUMN encrypt_field_config.field_order IS '字段加密执行顺序';
COMMENT ON COLUMN encrypt_field_config.skip_encrypted IS '是否跳过已加密数据(1=跳过,0=不跳过)';
COMMENT ON COLUMN encrypt_field_config.create_time IS '创建时间';
COMMENT ON COLUMN encrypt_field_config.update_time IS '更新时间';

-- encrypt_task
CREATE TABLE encrypt_task (
    id                      NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_status             VARCHAR2(32) NOT NULL,
    trigger_time            TIMESTAMP NOT NULL,
    finish_time             TIMESTAMP,
    trigger_user            VARCHAR2(64) NOT NULL,
    target_table_name       VARCHAR2(128) NOT NULL,
    target_field_list       VARCHAR2(1024) NOT NULL,
    total_record_count      NUMBER(20) DEFAULT 0,
    processed_record_count  NUMBER(20) DEFAULT 0,
    failed_record_count     NUMBER(20) DEFAULT 0,
    current_batch_no        NUMBER(10) DEFAULT 0,
    current_field_name      VARCHAR2(128),
    completed_field_list    VARCHAR2(1024),
    error_message           VARCHAR2(4000)
);

COMMENT ON TABLE encrypt_task IS '加密任务';
COMMENT ON COLUMN encrypt_task.id IS '任务ID';
COMMENT ON COLUMN encrypt_task.task_status IS '任务状态:PENDING/RUNNING/SUCCESS/PARTIAL_SUCCESS/FAILED/CANCELLED';
COMMENT ON COLUMN encrypt_task.trigger_time IS '触发时间';
COMMENT ON COLUMN encrypt_task.finish_time IS '完成时间';
COMMENT ON COLUMN encrypt_task.trigger_user IS '触发人';
COMMENT ON COLUMN encrypt_task.target_table_name IS '目标表名';
COMMENT ON COLUMN encrypt_task.target_field_list IS '目标字段列表(JSON)';
COMMENT ON COLUMN encrypt_task.total_record_count IS '总记录数';
COMMENT ON COLUMN encrypt_task.processed_record_count IS '已处理记录数';
COMMENT ON COLUMN encrypt_task.failed_record_count IS '失败记录数';
COMMENT ON COLUMN encrypt_task.current_batch_no IS '当前批次号';
COMMENT ON COLUMN encrypt_task.current_field_name IS '当前加密字段名';
COMMENT ON COLUMN encrypt_task.completed_field_list IS '已完成字段列表(逗号分隔)';
COMMENT ON COLUMN encrypt_task.error_message IS '异常信息摘要';

-- encrypt_task_error
CREATE TABLE encrypt_task_error (
    id                  NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id             NUMBER(20) NOT NULL,
    batch_no            NUMBER(10) NOT NULL,
    field_name          VARCHAR2(128) NOT NULL,
    record_primary_key  VARCHAR2(256) NOT NULL,
    error_code          VARCHAR2(64) NOT NULL,
    error_message       VARCHAR2(2000) NOT NULL,
    create_time         TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_error_task FOREIGN KEY (task_id) REFERENCES encrypt_task(id) ON DELETE CASCADE
);

COMMENT ON TABLE encrypt_task_error IS '加密异常记录';
COMMENT ON COLUMN encrypt_task_error.id IS '主键';
COMMENT ON COLUMN encrypt_task_error.task_id IS '关联任务ID';
COMMENT ON COLUMN encrypt_task_error.batch_no IS '批次号';
COMMENT ON COLUMN encrypt_task_error.field_name IS '失败字段名';
COMMENT ON COLUMN encrypt_task_error.record_primary_key IS '失败记录主键值';
COMMENT ON COLUMN encrypt_task_error.error_code IS '错误码';
COMMENT ON COLUMN encrypt_task_error.error_message IS '错误信息';
COMMENT ON COLUMN encrypt_task_error.create_time IS '创建时间';